projects:
  expoAmplifyApi-prod:
    schemaPath: graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        region: ap-northeast-1
        apiId: nv4bw3lfi5axzeauxjow4l2xzy
        maxDepth: 2
